import React from 'react';
import {
  Bell,
  AlertTriangle,
  CheckCircle2,
  Lock,
  Info,
  Star,
  X,
  Gem,
  Smile,
  Trophy,
  Circle,
  Clock as ClockIcon,
  Users,
  ArrowRight,
  Timer as TimerIcon,
  Play,
  Pause,
  RotateCcw,
  Volume2,
  VolumeX,
  MessageSquare,
  Activity,
  Map as MapIcon,
  BarChart3,
  Plus,
  Edit3,
  Save,
  Music,
  Flag,
  GraduationCap,
  Laptop,
  BookOpen,
  Quote,
  Monitor,
  Layout,
  Settings,
  AlignLeft,
  AlignCenter,
  Bold,
  Italic,
  Palette,
  Type,
  Gamepad2,
  Search,
  Link,
  Ghost,
  Minus,
  Trash2,
  Check,
  QrCode,
  Target,
  Network,
  ListTodo,
  Waves,
  Settings2,
  Sliders,
  Hourglass,
  StickyNote,
  ListChecks,
  CloudSun,
  Lightbulb,
  Calendar,
  CalendarDays,
  PartyPopper,
  Maximize,
  Minimize,
  Grid,
  Wifi,
  Watch,
  GlassWater,
  Ear,
  CheckSquare,
  Square,
  AlignJustify,
  Grid3X3,
  Maximize2,
  Heart,
  User,
  BookA,
  CircleDollarSign,
  Globe,
  Bot
} from 'lucide-react';

export const ALL_WIDGET_CONFIG = [
  { id: "tagesplan", icon: CalendarDays, label: "TAGESPLAN" },
  { id: "termine", icon: Bell, label: "TERMINE" },
  { id: "timer", icon: Watch, label: "ZEIT" },
  { id: "laerm", icon: VolumeX, label: "LÄRM" },
  { id: "groups", icon: Users, label: "GRUPPEN" },
  { id: "pause", icon: Pause, label: "PAUSE" },
  { id: "ampel", icon: Lightbulb, label: "AMPEL" },
  { id: "luuise", icon: Flag, label: "LUUISE" },
  { id: "klassenglas", icon: GlassWater, label: "GLAS" },
  { id: "classpet", icon: Ghost, label: "HAUSTIER" },
  { id: "sounds", icon: Music, label: "SOUND" },
  { id: "todo", icon: ListTodo, label: "TO-DO" },
  { id: "dienste", icon: CheckSquare, label: "DIENSTE" },
  { id: "riddle", icon: Lightbulb, label: "RÄTSEL" },
  { id: "quiz", icon: Target, label: "QUIZ" },
  { id: "mindmap", icon: Network, label: "MINDMAP" },
  { id: "lottowinner", icon: Trophy, label: "LOTTO" },
  { id: "lernwoerter", icon: BookA, label: "WÖRTER" },
  { id: "links", icon: Link, label: "LINK" },
  { id: "qrcode", icon: QrCode, label: "QR" },
  { id: "sticky", icon: StickyNote, label: "NOTIZ" },
  { id: "studentlist", icon: User, label: "SCHÜLER" },
  { id: "scoreboard", icon: Trophy, label: "PUNKTE" },
  { id: "wheel", icon: Circle, label: "GLÜCKSRAD" },
  { id: "breathing", icon: Waves, label: "ATEMÜBUNG" },
  { id: "kidweather", icon: CloudSun, label: "WETTERSTATION" },
  { id: "mathcards", icon: GraduationCap, label: "RECHNEN" },
  { id: "scrambler", icon: Type, label: "BAUKASTEN" },
  { id: "watertracker", icon: GlassWater, label: "WASSER" },
  { id: "wordchain", icon: Link, label: "WORTKETTE" },
  { id: "moodmeter", icon: Smile, label: "STIMMUNG" },
  { id: "colormixer", icon: Palette, label: "FARBMISCHER" },
  { id: "secretcode", icon: Lock, label: "KRYPTOBOX" },
  { id: "clockpuzzle", icon: ClockIcon, label: "UHRENTRAINER" },
  { id: "fractiongrid", icon: Grid, label: "BRUCHTEILE" },
  { id: "trafficquiz", icon: GraduationCap, label: "FAHRRAD" },
  { id: "wordbuilder", icon: BookOpen, label: "SILBEN" },
  { id: "watercycle", icon: Waves, label: "WASSERKREISLAUF" },
  { id: "soundmachine", icon: Music, label: "KLANG" },
  { id: "mathbalancer", icon: Sliders, label: "WAAGE" },
  { id: "animalvoice", icon: Bot, label: "ROBOTER-SOUNDS" },
  { id: "constellation", icon: Star, label: "STERNBILDER" },
  { id: "multitrainer", icon: GraduationCap, label: "EINMALEINS" },
  { id: "moneycalc", icon: CircleDollarSign, label: "GELDBÖRSE" },
  { id: "storyemojis", icon: MessageSquare, label: "STORY-WÜRFEL" },
  { id: "abcorder", icon: Type, label: "ABC-SORTIERER" },
  { id: "planetarium", icon: Globe, label: "PLANETARIUM" },
  { id: "anschauung", icon: Grid3X3, label: "ANSCHAUUNG" },
];
